SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

DROP TABLE IF EXISTS `dac_view_current_assessments`;
DROP VIEW IF EXISTS `dac_view_current_assessments`;

DROP TABLE IF EXISTS `dac_ReportVersion`;
DROP TABLE IF EXISTS `dac_ReportPermission`;
DROP TABLE IF EXISTS `dac_Report`;
DROP TABLE IF EXISTS `dac_AnnouncementSystemUserRead`;
DROP TABLE IF EXISTS `dac_Announcement`;
DROP TABLE IF EXISTS `dac_AssessmentGroupAssessmentBlob`;
DROP TABLE IF EXISTS `dac_AssessmentResultBlob`;
DROP TABLE IF EXISTS `dac_AssessmentGroupPermission`;
DROP TABLE IF EXISTS `dac_AssignmentItem`;
DROP TABLE IF EXISTS `dac_Assignment`;
DROP TABLE IF EXISTS `dac_AssessmentBlob`;
DROP TABLE IF EXISTS `dac_AssessmentGroup`;
DROP TABLE IF EXISTS `dac_LibraryAssetBlobTag`;
DROP TABLE IF EXISTS `dac_LibraryAssetResultBlob`;
DROP TABLE IF EXISTS `dac_LibraryAssetBlob`;


DROP TABLE IF EXISTS `dac_Tag`;
DROP TABLE IF EXISTS `dac_SystemVersion`;
DROP TABLE IF EXISTS `dac_migrations`;
DROP TABLE IF EXISTS `dac_Role`;
DROP TABLE IF EXISTS `dac_HostSite`;

SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
