<?php

namespace OpenEMR\Modules\DiscoverAndChange\Assessments\Models;

class AssignedQuestionnaire extends Assignment
{
    /**
     * @var int|null $documentTemplateId The id of the onsite_documents.id record if this questionnaire assignment comes from a profile
     */
    private ?int $documentTemplateId;

    /**
     * @var string|null $documentId The uuid of the saved off documents.uuid record if this questionnaire assignment comes from a profile. Note this is the string, not binary representation.
     */
    private ?string $documentId;

    private string $questionnaireId;
    private ?string $resultId;

    public function __construct()
    {
        parent::__construct();
        $this->resultId = null;
        $this->documentId = null;
        $this->documentTemplateId = null;
        $this->setType("Questionnaire");
    }

    /**
     * @return string
     */
    public function getQuestionnaireId(): string
    {
        return $this->questionnaireId;
    }

    /**
     * @param string $assetId
     */
    public function setQuestionnaireId(string $questionnaireId): void
    {
        $this->questionnaireId = $questionnaireId;
    }


    public function getResultId(): ?string
    {
        return $this->resultId;
    }

    public function setResultId(?string $v)
    {
        $this->resultId = $v;
        if ($v !== null) {
            $this->setDateCompleted(new \DateTime());
        }
    }

    /**
     * @return int|null
     */
    public function getDocumentTemplateId(): ?int
    {
        return $this->documentTemplateId;
    }

    /**
     * @param int|null $documentTemplateId
     * @return AssignedQuestionnaire
     */
    public function setDocumentTemplateId(?int $documentTemplateId): AssignedQuestionnaire
    {
        $this->documentTemplateId = $documentTemplateId;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getDocumentId(): ?string
    {
        return $this->documentId;
    }

    /**
     * @param string|null $documentId The uuid representing this document
     * @return AssignedQuestionnaire
     */
    public function setDocumentId(?string $documentId): AssignedQuestionnaire
    {
        $this->documentId = $documentId;
        return $this;
    }


    public function jsonSerialize()
    {
        $result = parent::jsonSerialize(); // TODO: Change the autogenerated stub
        return array_merge($result, [
            "questionnaireId" => $this->getQuestionnaireId()
            ,'resultId' => $this->getResultId() ?? null
            ,'documentTemplateId' => $this->getDocumentTemplateId() ?? null
            ,'documentId' => $this->getDocumentId() ?? null
        ]);
    }

    public function fromJSON(array $assignmentJSON)
    {
        parent::fromJSON($assignmentJSON);
        $this->setQuestionnaireId($assignmentJSON['questionnaireId'] ?? 0);
    }
}
