<?php

namespace OpenEMR\Modules\DiscoverAndChange\Assessments\Models;

use DateTime;

class AssignedAssessment extends Assignment
{
    private string $assessmentUuid;
    private string $assessmentId;
    private string $uid;
    private ?string $resultId;
    private ?int $itemId;

    public function __construct()
    {
        parent::__construct();
        $this->uid = "";
        $this->assessmentUuid = "";
        $this->setType("Assessment");
        $this->resultId = null;
        $this->itemId = null;
    }

    public function getItemId(): ?int
    {
        return $this->itemId;
    }

    /** @return void */
    public function setItemId(?int $v)
    {
        $this->itemId = $v;
    }

    /**
     * @return string
     */
    public function getAssessmentUuid(): string
    {
        return $this->assessmentUuid;
    }

    /**
     * @param string $assessmentUuid
     */
    public function setAssessmentUuid(string $assessmentUuid): void
    {
        $this->assessmentUuid = $assessmentUuid;
    }

    public function getAssessmentId(): int
    {
        return $this->assessmentId;
    }

    /** @return void */
    public function setAssessmentId(int $v)
    {
        $this->assessmentId = $v;
    }

    public function getUid(): string
    {
        return $this->uid;
    }

    /** @return void */
    public function setUid(string $v)
    {
        $this->uid = $v;
    }

    public function getResultId(): ?string
    {
        return $this->resultId;
    }

    /** @return void */
    public function setResultId(?string $v)
    {
        $this->resultId = $v;
        if ($v !== null) {
            $this->setDateCompleted(new \DateTime());
        }
    }

    /** @return array<mixed> */
    public function jsonSerialize(): array
    {
        $json =  parent::jsonSerialize(); // TODO: Change the autogenerated stub
        return array_merge($json, [
            'assessmentId' => $this->getAssessmentId(),
            'uid' => $this->getUid(),
            'assessmentUuid' => $this->getAssessmentUuid(),
            'resultId' => $this->getResultId(),
            'itemId' => $this->getItemId()
        ]);
    }
    /**
     * @param array<mixed> $assignmentJSON
     * @return void
     */
    public function fromJSON(array $assignmentJSON)
    {
        parent::fromJSON($assignmentJSON);
        $this->setAssessmentId($assignmentJSON['assessmentId'] ?? 0);
        $this->setUid($assignmentJSON['uid'] ?? '');
        $this->setAssessmentUuid($assignmentJSON['assessmentUuid'] ?? '');
        $this->setResultId($assignmentJSON['resultId'] ?? null);
        $this->setItemId($assignmentJSON['itemId'] ?? 0);
    }
}
