<?php

namespace OpenEMR\Modules\DiscoverAndChange\Assessments\Models;

class AssignedLibraryAsset extends Assignment
{
    private int $assetId;
    private ?string $resultId;
    private ?string $assetUuid;

    public function __construct()
    {
        parent::__construct();
        $this->resultId = null;
        $this->assetUuid = null;
        $this->setType("LibraryAsset");
    }

    public function getAssetUuid(): ?string
    {
        return $this->assetUuid;
    }

    /**
     * @param string|null $assetUuid
     */
    public function setAssetUuid(?string $assetUuid): void
    {
        $this->assetUuid = $assetUuid;
    }

    /**
     * @return int
     */
    public function getAssetId(): int
    {
        return $this->assetId;
    }

    /**
     * @param int $assetId
     */
    public function setAssetId(int $assetId): void
    {
        $this->assetId = $assetId;
    }


    public function getResultId(): ?string
    {
        return $this->resultId;
    }

    /** @return void */
    public function setResultId(?string $v)
    {
        $this->resultId = $v;
        if ($v !== null) {
            $this->setDateCompleted(new \DateTime());
        }
    }

    /** @return array<mixed> */
    public function jsonSerialize(): array
    {
        $result = parent::jsonSerialize(); // TODO: Change the autogenerated stub
        return array_merge($result, [
            "assetId" => $this->getAssetId()
            ,'resultId' => $this->getResultId() ?? null
            ,'assetUuid' => $this->getAssetUuid() ?? ''
        ]);
    }

    /**
     * @param array<mixed> $assignmentJSON
     * @return void
     */
    public function fromJSON(array $assignmentJSON)
    {
        parent::fromJSON($assignmentJSON);
        $this->setAssetId(($assignmentJSON['assetId'] ?? 0));
        $this->setAssetUuid(($assignmentJSON['assetUuid'] ?? ''));
    }
}
