<?php

namespace OpenEMR\Modules\DiscoverAndChange\Assessments\Models;

class AssignedQuestionnaire extends Assignment
{
    /**
     * @var int|null $documentTemplateId The id of the onsite_documents.id record if this questionnaire assignment comes from a profile
     */
    private ?int $documentTemplateId;

    /**
     * @var string|null $documentId The uuid of the saved off documents.uuid record if this questionnaire assignment comes from a profile. Note this is the string, not binary representation.
     */
    private ?string $documentId;

    private string $questionnaireId;
    private ?string $resultId;

    public function __construct()
    {
        parent::__construct();
        $this->resultId = null;
        $this->documentId = null;
        $this->documentTemplateId = null;
        $this->setType("Questionnaire");
    }

    /**
     * @return string
     */
    public function getQuestionnaireId(): string
    {
        return $this->questionnaireId;
    }

    /**
     * @param string $questionnaireId
     */
    public function setQuestionnaireId(string $questionnaireId): void
    {
        $this->questionnaireId = $questionnaireId;
    }


    public function getResultId(): ?string
    {
        return $this->resultId;
    }

    /** @return void */
    public function setResultId(?string $v)
    {
        $this->resultId = $v;
        if ($v !== null) {
            $this->setDateCompleted(new \DateTime());
        }
    }

    /**
     * @return int|null
     */
    public function getDocumentTemplateId(): ?int
    {
        return $this->documentTemplateId;
    }

    /**
     * @param int|null $documentTemplateId
     * @return AssignedQuestionnaire
     */
    public function setDocumentTemplateId(?int $documentTemplateId): AssignedQuestionnaire
    {
        $this->documentTemplateId = $documentTemplateId;
        return $this;
    }

    /**
     * @return string|null
     */
    public function getDocumentId(): ?string
    {
        return $this->documentId;
    }

    /**
     * @param string|null $documentId The uuid representing this document
     * @return AssignedQuestionnaire
     */
    public function setDocumentId(?string $documentId): AssignedQuestionnaire
    {
        $this->documentId = $documentId;
        return $this;
    }


    /** @return array<mixed> */
    public function jsonSerialize(): array
    {
        $result = parent::jsonSerialize(); // TODO: Change the autogenerated stub
        return array_merge($result, [
            "questionnaireId" => $this->getQuestionnaireId()
            ,'resultId' => $this->getResultId() ?? null
            ,'documentTemplateId' => $this->getDocumentTemplateId() ?? null
            ,'documentId' => $this->getDocumentId() ?? null
        ]);
    }

    /**
     * @param array<mixed> $assignmentJSON
     * @return void
     */
    public function fromJSON(array $assignmentJSON)
    {
        parent::fromJSON($assignmentJSON);
        /** @var string $questionnaireId */
        $questionnaireId = $assignmentJSON['questionnaireId'] ?? '';
        $this->setQuestionnaireId($questionnaireId);
        // Previously resultId/documentId/documentTemplateId were emitted by
        // jsonSerialize() but never read back here, so a serialize -> fromJSON round
        // trip silently dropped them. Hydrate them for a symmetric round trip.
        if (array_key_exists('documentId', $assignmentJSON)) {
            /** @var string|null $documentId */
            $documentId = $assignmentJSON['documentId'];
            $this->setDocumentId($documentId);
        }
        if (array_key_exists('documentTemplateId', $assignmentJSON)) {
            $documentTemplateId = $assignmentJSON['documentTemplateId'];
            $this->setDocumentTemplateId(is_numeric($documentTemplateId) ? (int)$documentTemplateId : null);
        }
        if (array_key_exists('resultId', $assignmentJSON)) {
            /** @var string|null $resultId */
            $resultId = $assignmentJSON['resultId'];
            // setResultId(non-null) resets dateCompleted to "now", so preserve the value
            // the parent already parsed from the payload and restore it afterwards.
            $preservedDateCompleted = $this->getDateCompleted();
            $this->setResultId($resultId);
            if ($preservedDateCompleted !== null) {
                $this->setDateCompleted($preservedDateCompleted);
            }
        }
    }
}
